# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5QDcUbwrLf4cp5qAlW0Lu7NyXm0LOSu
"""

import pandas as pd

def load_data():
    # Load analyzed data from Task 1
    return pd.read_csv('financial_data.csv')

def financial_chatbot(user_query):
    query = user_query.strip().lower()

    # Predefined Query 1: Total Revenue
    if "total revenue" in query:
        return (
            "Total Revenue (FY 2025):\n"
            "- Microsoft: $281,724 million (+14.93% YoY)\n"
            "- Apple: $416,161 million (+6.42% YoY)\n"
            "- Tesla: $94,827 million (-2.93% YoY)"
        )

    # Predefined Query 2: Net Income Change
    elif "net income" in query:
        return (
            "Net Income Growth (FY 2025 vs FY 2024):\n"
            "- Apple: $112,010 million (+19.49% YoY)\n"
            "- Microsoft: $101,833 million (+15.54% YoY)\n"
            "- Tesla: $3,794 million (-46.50% YoY)"
        )

    # Predefined Query 3: Operating Cash Flow
    elif "cash flow" in query or "operating cash" in query:
        return (
            "Operating Cash Flow (FY 2025):\n"
            "- Microsoft: $136,284 million\n"
            "- Apple: $111,482 million\n"
            "- Tesla: $14,747 million"
        )

    # Predefined Query 4: Total Assets vs Liabilities
    elif "assets" in query or "liabilities" in query:
        return (
            "Balance Sheet Overview (FY 2025):\n"
            "- Microsoft: Assets = $620,211M | Liabilities = $273,412M\n"
            "- Apple: Assets = $359,241M | Liabilities = $285,508M\n"
            "- Tesla: Assets = $137,806M | Liabilities = $54,941M"
        )

    else:
        return "Sorry, I can only provide information on predefined financial queries regarding Revenue, Net Income, Cash Flow, and Balance Sheet totals."

if __name__ == "__main__":
    print("--- BCG Financial AI Chatbot Prototype ---")
    print("Type 'exit' to quit.\n")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'exit':
            break
        response = financial_chatbot(user_input)
        print(f"Bot:\n{response}\n")